CREATE DATABASE DB_GIAOVIEN
GO

USE DB_GIAOVIEN
GO

--------------------------------------------------- [ KHỞI TẠO CÁC BẢNG DỮ LIỆU ] ---------------------------------------------------
--------------------- BẢNG GIÁO VIÊN
CREATE TABLE GIAOVIEN
(
	MAGV			VARCHAR(10),
	HOTEN			NVARCHAR(50),
	NGAYSINH		DATE,
	MATKHAU			VARCHAR(15),
	GIOITINH		NVARCHAR(5),
	DIACHI			NVARCHAR(100),
	SODIENTHOAI		VARCHAR(10),
	EMAIL			VARCHAR(30),
	THAMNIEN		INT,
	MASOCD			VARCHAR(10),
	BAC				NVARCHAR(10),
	MACM			VARCHAR(10),
	MAQTC			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MAGV)
);

--------------------- BẢNG CHỨC VỤ
CREATE TABLE CHUCVU
(
	MACV			VARCHAR(10) NOT NULL,
	TENCV			NVARCHAR(50),
	DINHMUCTIETDAY	DECIMAL(18,2),
	CONSTRAINT PK_CHUCVU PRIMARY KEY(MACV)
);

--------------------- BẢNG CHI TIẾT CHỨC VỤ
CREATE TABLE CHITIETCHUCVU
(
	MACV			VARCHAR(10) NOT NULL,
	MAGV			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CHITIETCHUCVU PRIMARY KEY(MAGV, MACV)
);

--------------------- BẢNG CHỨC DANH
CREATE TABLE CHUCDANH
(
	MASOCD			VARCHAR(10) NOT NULL,
	HANGCD			NVARCHAR(10),
	CONSTRAINT PK_CHUCDANH PRIMARY KEY(MASOCD)
);

--------------------- BẢNG BẬC LƯƠNG
CREATE TABLE BACLUONG
(
	MASOCD			VARCHAR(10) NOT NULL,
	BAC				NVARCHAR(10) NOT NULL,
	HESOLUONG		DECIMAL(18,2),
	CONSTRAINT PK_BACLUONG PRIMARY KEY(MASOCD, BAC)
);

--------------------- BẢNG LỚP HỌC
CREATE TABLE LOPHOC
(
	MALP			VARCHAR(10) NOT NULL,
	TENLP			NVARCHAR(20),
	SISO			INT,
	KHIEMKHUYET		BIT,
	CONSTRAINT PK_LOPHOC PRIMARY KEY(MALP)
);

--------------------- BẢNG CHỦ NHIỆM
CREATE TABLE CHUNHIEM
(
	MALP			VARCHAR(10) NOT NULL,
	MAGV			VARCHAR(10) NOT NULL,
	NAMHOC		VARCHAR(15),
	CONSTRAINT PK_CHUNHIEM PRIMARY KEY(MALP)
);

--------------------- BẢNG BẰNG CẤP
CREATE TABLE BANGCAP
(
	MABC			VARCHAR(10) NOT NULL,
	TENBC			VARCHAR(50),
	CONSTRAINT PK_BANGCAP PRIMARY KEY(MABC)
);

--------------------- BẢNG CHI TIẾT BẰNG CẤP
CREATE TABLE CHITIETBANGCAP
(
	MABC			VARCHAR(10) NOT NULL,
	MAGV			VARCHAR(10) NOT NULL,
	NGAYCAP			DATE,
	CONSTRAINT PK_CHITIETBANGCAP PRIMARY KEY(MABC, MAGV)
);

--------------------- BẢNG CHUYÊN MÔN
CREATE TABLE CHUYENMON
(
	MACM			VARCHAR(10) NOT NULL,
	TENCM			VARCHAR(50),
	CONSTRAINT PK_CHUYENMON PRIMARY KEY(MACM)
);

--------------------- BẢNG QUYỀN TRUY CẬP
CREATE TABLE QUYENTRUYCAP
(
	MAQTC			VARCHAR(10) NOT NULL,
	TENQTC			VARCHAR(50),
	CONSTRAINT PK_QUYENTRUYCAP PRIMARY KEY(MAQTC)
);

--------------------------------------------------- [ RÀNG BUỘC ] ---------------------------------------------------

--------------------------------------------------------- KHÓA NGOẠI
--------------------- BẢNG BẬC LƯƠNG
ALTER TABLE BACLUONG 
ADD CONSTRAINT FK_BACLUONG_CHUCDANH FOREIGN KEY(MASOCD) REFERENCES CHUCDANH(MASOCD)

--------------------- BẢNG GIÁO VIÊN
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT FK_GIAOVIEN_BACLUONG FOREIGN KEY(MASOCD, BAC) REFERENCES BACLUONG(MASOCD, BAC),
	CONSTRAINT FK_GIAOVIEN_QUYENTRUYCAP FOREIGN KEY(MAQTC) REFERENCES QUYENTRUYCAP(MAQTC),
	CONSTRAINT FK_GIAOVIEN_CHUYENMON FOREIGN KEY(MACM) REFERENCES CHUYENMON(MACM)

--------------------- BẢNG CHỦ NHIỆM
ALTER TABLE CHUNHIEM 
ADD CONSTRAINT FK_CHUNHIEM_LOPHOC FOREIGN KEY(MALP) REFERENCES LOPHOC(MALP),
	CONSTRAINT FK_CHUNHIEM_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV)

--------------------- BẢNG CHI TIẾT CHỨC VỤ
ALTER TABLE CHITIETCHUCVU
ADD CONSTRAINT FK_CHITIETCHUCVU_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV),
	CONSTRAINT FK_CHITIETCHUCVU_CHUCVU FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV)

--------------------- BẢNG CHI TIẾT BẰNG CẤP
ALTER TABLE CHITIETBANGCAP
ADD CONSTRAINT FK_CHITIETBANGCAP_GIAOVIEN FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV),
	CONSTRAINT FK_CHITIETBANGCAP_BANGCAP FOREIGN KEY(MABC) REFERENCES BANGCAP(MABC)


--------------------------------------------------------- TRIGGER
--------------------- TRIGGER TẠO RANDOM MÃ GIÁO VIÊN 
CREATE TRIGGER TAONGAUNHIENMAGIAOVIEN
ON GIAOVIEN
AFTER INSERT
AS
BEGIN    
    UPDATE GIAOVIEN
    SET MAGV = LEFT(CAST(ABS(CHECKSUM(NEWID())) AS VARCHAR(10)), 10)
END